" sod vi we want full fat vim
set nocompatible

" Basic Settings
set nu
set expandtab
set sw=4
set ts=4

" swapfiles are useful
set swapfile

" cluttered ~files are not
set dir=/tmp

" Leader
let leader = '\\'

" Terminal Encoding
set t_Co=16

"-----------------------------------------------------
" START automated install of vundle
"-----------------------------------------------------
let vundle_plugin_trigger=expand('~/.vim/bundle/vundle-managed/installed.txt')
let vundle_plugins_installed = 1
if !filereadable(vundle_plugin_trigger)
    silent !mkdir -p ~/.vim/bundle/vundle-managed
    let vundle_plugins_installed = 0
endif

"-----------------------------------------------------
" START plugin section
"-----------------------------------------------------
filetype off " force reloading *after* pathogen loaded
set rtp+=~/dotfiles/bundle/vundle
call vundle#begin('~/.vim/bundle/vundle-managed')

Plugin 'VundleVim/Vundle.vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'tpope/vim-fugitive.git'

" close xml tags
Plugin 'alvan/vim-closetag'

" groovy indenting
Bundle 'https://github.com/vim-scripts/groovyindent-unix.git'
Bundle 'https://github.com/vim-scripts/groovy.vim.git'

" ansible syntax
"Plugin 'pearofducks/ansible-vim'
Bundle 'chase/vim-ansible-yaml'

" tagview
Bundle 'https://github.com/majutsushi/tagbar.git'

" cscope maps
Bundle 'https://github.com/steffanc/cscopemaps.vim.git'

" trigger automated install of plugins
if vundle_plugins_installed == 0
    :PluginInstall
    silent !touch ~/.vim/bundle/vundle-managed/installed.txt
endif

call vundle#end()
"-----------------------------------------------------
" STOP plugin section
"-----------------------------------------------------

"must be last
filetype plugin indent on " load filetype plugins/indent settings
syntax enable
set background=dark

" solarized is better for diffs
colorscheme delek
if &diff                                " pretty colours
    set background=dark " dark | light "
    colorscheme solarized
endif

" open diffs in vsplits
set diffopt+=vertical

" eat trailing whitespace
autocmd BufWritePre * :%s/\s\+$//e

" Jenkinsfiles are groovy
au BufReadPost Jenkinsfile set syntax=groovy

let g:closetag_filenames = "*.html,*.xhtml,*.phtml,*.xml"

" setup tagbar
let g:tagbar_width = 120
let g:tagbar_left  = 1

" make the quickfix window open in a new tab with local mapping
autocmd FileType qf nnoremap <buffer> <Enter> <C-W><Enter><C-W>T

"magic things happen when i type this stuf
"ab = abreviation keyword
"%:t is tail
"%:r is root
ab xclass <C-R>=expand('%:t:r')<CR>

nmap <leader>jj :make -j8 check<CR>
nmap <silent> <Right> :next<CR>
nmap <silent> <Left> :prev<CR>
