" sod vi we want full fat vim
set nocompatible

" Basic Settings
set nu
set expandtab
set sw=4
set ts=4

" swapfiles are useful
set swapfile

" cluttered ~files are not
set dir=/tmp

" Leader
let leader = '\\'

" Terminal Encoding
set t_Co=16

"-----------------------------------------------------
" START automated install of vundle
"-----------------------------------------------------
let vundle_plugin_trigger=expand('~/.vim/bundle/vundle-managed/installed.txt')
let vundle_plugins_installed = 1
if !filereadable(vundle_plugin_trigger)
    silent !mkdir -p ~/.vim/bundle/vundle-managed
    let vundle_plugins_installed = 0
endif

"-----------------------------------------------------
" START plugin section
"-----------------------------------------------------
filetype off " force reloading *after* pathogen loaded
set rtp+=~/dotfiles/bundle/vundle
call vundle#begin('~/.vim/bundle/vundle-managed')

Plugin 'VundleVim/Vundle.vim'
Plugin 'altercation/vim-colors-solarized'

" trigger automated install of plugins
if vundle_plugins_installed == 0
    :PluginInstall
    silent !touch ~/.vim/bundle/vundle-managed/installed.txt
endif

call vundle#end()
"-----------------------------------------------------
" STOP plugin section
"-----------------------------------------------------

"must be last
filetype plugin indent on " load filetype plugins/indent settings
syntax enable
set background=dark
colorscheme solarized
